name: Deploy to Server

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build project
        env:
          BASE_URL: "/${{ github.ref_name }}"
        run: yarn build

      - name: Deploy to Server
        env:
          DEST_FOLDER: ${{ github.ref_name }}
          BASE_DIR: "/var/www/ch05522979/www/simple-calculator.vkvaskov.com"
        run: |
          # Change directory to BASE_DIR
          cd $BASE_DIR || { echo "Failed to change directory to $BASE_DIR." >&2; exit 1; }

          # Create the destination folder if it doesn't exist
          mkdir -p $DEST_FOLDER || { echo "Failed to create destination folder." >&2; exit 1; }

          # Move the built files to the destination folder
          cp -r $GITHUB_WORKSPACE/dist/* $DEST_FOLDER/ || { echo "Failed to copy files." >&2; exit 1; }

          echo "Deployment completed successfully."

          # Display disk usage of the destination folder
          echo "Displaying disk usage of the destination folder..."
          du -sh $DEST_FOLDER
