name: Deploy to SSH Server

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Yarn
        run: |
          echo "Installing Yarn..."
          npm install -g yarn

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          yarn install

      - name: Build project
        run: |
          echo "Building project..."
          yarn build

      - name: Install SSH client and diagnostic tools
        run: |
          echo "Installing SSH client and diagnostic tools..."
          apt-get update
          apt-get install -y openssh-client iputils-ping telnet

      - name: Deploy to SSH Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          BRANCH_NAME: ${{ github.ref_name }}
          DEST_FOLDER: "/www/simple-calculator.vkvaskov.com/${{ github.ref_name }}"
        run: |
          set -e
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh || { echo "Failed to create .ssh directory" >&2; exit 1; }
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa || { echo "Failed to write SSH private key" >&2; exit 1; }
          chmod 600 ~/.ssh/id_rsa || { echo "Failed to change permissions on SSH private key" >&2; exit 1; }
          echo "SSH key setup completed."

          # Log the destination folder path
          echo "Destination Folder: $DEST_FOLDER"

          # Check if we can connect to the server
          echo "Testing SSH connection..."
          ssh -v $SSH_USER@$SSH_HOST "echo 'SSH connection successful.'" || { echo "SSH connection failed." >&2; exit 1; }

          # Create the destination folder
          echo "Creating destination folder..."
          ssh -v $SSH_USER@$SSH_HOST "mkdir -p $DEST_FOLDER" || { echo "Failed to create destination folder." >&2; exit 1; }

          # Perform the rsync operation
          echo "Starting rsync..."
          rsync -avz --delete ./dist/ $SSH_USER@$SSH_HOST:$DEST_FOLDER/ || { echo "Rsync failed." >&2; exit 1; }

          echo "Deployment completed successfully."
